name: chinese-flute-demucs
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pytorch>=2.0
  - torchaudio>=2.0
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  - soundfile>=0.12
  - numpy
  - pip:
      - dora-search
      - hydra-core
      - julius
      - museval>=0.4
      - librosa>=0.10
      # Dev / docs
      - jupyter
      - ipykernel
      - nbmake
      - matplotlib
      - mkdocs-material
      - "mkdocstrings[python]"
      - mkdocs-jupyter
      - pytest
